services:
  - type: web
    name: e-commerce-store
    env: node
    rootDir: . # This tells Render to use root directory
    buildCommand: npm run render-build
    startCommand: npm run render-start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    regions:
      - oregon
