services:
  - type: web
    name: e-commerce-store-backend
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm run render-start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    regions:
      - oregon
